'use client';

import '../globals.css';
import type {Metadata} from 'next';
import {Inter, Titillium_Web} from 'next/font/google';
import {usePathname, useSearchParams} from 'next/navigation';
import {useEffect} from 'react';

import ErrorBoundaryHandler from './error';

const inter = Inter({subsets: ['latin']});
const titilliumWeb = Titillium_Web({
  subsets: ['latin'],
  weight: ['400', '600', '700', '900'],
});

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <head>
        <title>Carefreeav</title>

        <link rel='icon' type='image/x-icon' href='/images/pp.ico' />
      </head>
      <body className={titilliumWeb.className}>
        <ErrorBoundaryHandler>
          <>
            <div className='h-screen flex justify-center items-center w-screen'>
              <h1 className='text-4xl'>Site under construction</h1>
            </div>
          </>
        </ErrorBoundaryHandler>
      </body>
    </html>
  );
}

export function NavigationEvents() {
  const pathname = usePathname();
  const searchParams = useSearchParams();

  useEffect(() => {
    const url = `${pathname}?${searchParams}`;
    // You can now use the current URL
    // ...
  }, [pathname, searchParams]);

  return null;
}
